spring:
  application:
    name: ${env.SERVICE_NAME:user-service}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/market_note}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      continue-on-error: true

  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    access-token:
      ttl: ${ACCESS_TOKEN_EXPIRATION_TIME:18000001800000}
    refresh-token:
      ttl: ${REFRESH_TOKEN_EXPIRATION_TIME:1209600000}

client:
  origin: ${CLIENT_ORIGIN:http://localhost:3000}
  cookie-domain: ${COOKIE_DOMAIN:localhost}
  cors:
    allowed-origins: ${ACCESS_CONTROL_ALLOWED_ORIGINS:http://localhost:3000}

server:
  origin: ${SERVER_ORIGIN:http://localhost:8080}
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: ERROR

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID:abc}
    client-secret: ${GOOGLE_CLIENT_SECRET:def}
  kakao:
    client-id: ${KAKAO_CLIENT_ID:abc}
    client-secret: ${KAKAO_CLIENT_SECRET:def}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
