spring:
  application:
    name: ${env.SERVICE_NAME:order-service}

  jwt:
    secret: ${JWT_SECRET_KEY:dev-secret-change-me}
    admin-access-token: ${JWT_ADMIN_ACCESS_TOKEN:abc}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marketnote_order}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      continue-on-error: true

client:
  origin: ${CLIENT_ORIGIN:http://localhost:3000}
  cookie-domain: ${COOKIE_DOMAIN:localhost}
  cors:
    allowed-origins: ${ACCESS_CONTROL_ALLOWED_ORIGINS:http://localhost:3000}

server:
  origin: ${SERVER_ORIGIN:http://localhost:8082}
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: ERROR

product-service:
  base-url: ${PRODUCT_SERVICE_SERVER_ORIGIN:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
