spring:
  application:
    name: shop-reward

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://localhost:3307/shop_reward?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

  batch:
    jdbc:
      initialize-schema: never
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-mariadb.sql
      continue-on-error: true      #?? CREATE ?? ???

  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    access-token:
      ttl: 1209600000000
    refresh-token:
      ttl: 1209600000

info:
  app:
    name: ??????
    description: ??? ???

# Custom configuration - ?? ?? ???
client:
  origin: ${CLIENT_ORIGIN:http://localhost:3000}
  cookie-domain: ${COOKIE_DOMAIN:localhost}
  cors:
    allowed-origins: ${ACCESS_CONTROL_ALLOWED_ORIGINS:http://localhost:3000}

server:
  origin: ${SERVER_ORIGIN:http://localhost:8080}
  error:
    # ?? ??? exception? ??? ???? ??
    include-exception: true

    # ?? ??? stacktrace ??? ???? ?? (ALWAYS, NEVER, ON_TRACE_PARAM)
    include-stacktrace: ALWAYS

    whitelabel:
      enabled: false


resources:
  static-resource-path: ${STATIC_RESOURCE_PATH:none}

# Logging Levels
logging:
  level:
    org.springframework.security: error

matching:
  algorithm:
    admin-id: 2
  partner-selector:
    study-field-similarity-weight: 0.5
  job:
    defaults:
      # template-id: "1"
      # k-value: "1"
      # nearest-neighbors: "3"
      # chunk-size: "1000"
      save-results-chunk-size: "100"
  manual:
    max-members-for-manual-matching: 10000
  scheduler:
    cron: "0 0 12 * * SAT"
    enabled: false

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID:abc}
    client-secret: ${GOOGLE_CLIENT_SECRET:def}
  kakao:
    client-id: ${KAKAO_CLIENT_ID:abc}
    client-secret: ${KAKAO_CLIENT_SECRET:def}
