spring:
  application:
    name: ${env.SERVICE_NAME:fulfillment-service}
  jackson:
    time-zone: Asia/Seoul

  jwt:
    secret: ${JWT_SECRET_KEY:dev-secret-change-me}
    admin-access-token: ${JWT_ADMIN_ACCESS_TOKEN:abc}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marketnote_fulfillment}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      continue-on-error: true

client:
  origin: ${CLIENT_ORIGIN:http://localhost:3000}
  cookie-domain: ${COOKIE_DOMAIN:localhost}
  cors:
    allowed-origins: ${ACCESS_CONTROL_ALLOWED_ORIGINS:http://localhost:3000}

server:
  origin: ${SERVER_ORIGIN:http://localhost:8085}
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false

vendor:
  fassto:
    auth:
      base-url: ${FASSTO_BASE_URL:abc}
      api-cd: ${FASSTO_API_CD:change-me}
      api-key: ${FASSTO_API_KEY:change-me}

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
