spring:
  application:
    name: ${env.SERVICE_NAME:file-service}
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

  jwt:
    secret: ${JWT_SECRET_KEY:dev-secret-change-me}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marketnote_file}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      continue-on-error: true

client:
  origin: ${CLIENT_ORIGIN:http://localhost:3000}
  cookie-domain: ${COOKIE_DOMAIN:localhost}
  cors:
    allowed-origins: ${ACCESS_CONTROL_ALLOWED_ORIGINS:http://localhost:3000}

server:
  origin: ${SERVER_ORIGIN:http://localhost:8080}
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

file:
  s3:
    credentials:
      access-key: ${S3_ACCESS_KEY:abc}
      secret-key: ${S3_SECRET_KEY:def}
    region:
      static: ${S3_REGION:ap-northeast-2}
    bucket-name: ${S3_BUCKET_NAME:ghi}
