global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'shop-reward'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'shop-reward-lb-1014721585.ap-northeast-2.elb.amazonaws.com:80' ]
