global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'market-note'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'users.market-note.store:443'
    scheme: https