global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'market-note'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'market-note-lb-1014721585.ap-northeast-2.elb.amazonaws.com:80' ]
